server {
    listen 80;
    server_name ntngoclinh.id.vn;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }

    location /api/tacke {
        proxy_pass http://my_nodered:1880/api/tacke;
    }
}

server {
    listen 80;
    server_name web2.ntngoclinh.id.vn;

    location / {
        root /usr/share/nginx/html/web2;
        index index.html;
    }
}