services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./web1:/usr/share/nginx/html/web1
      - ./web2:/usr/share/nginx/html/web2

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: my_cloudflared
    restart: always
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZWZiMzVhMzM5MDcyOTkwNzZmYTllNGExZWI4NTFlNzAiLCJzIjoiekF5UWc0TVF0bTFvZmNncXFtQXMzeVZMVUx5UktCU3NyNmFYSnBMcXNoMD0iLCJ0IjoiYmQyNjBkNjktMjg4Zi00OTNhLWIxZTgtMzFhMDhlNjNmMjRkIn0=
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml

  node-red:
    image: nodered/node-red:latest
    container_name: my_nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    restart: always

volumes:
  node_red_data: