# --- WEBSITE 1 ---
server {
    listen 80;
    server_name ngoclinh1.tnut.cuong.id.vn;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }

    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# --- WEBSITE 2 ---
server {
    listen 80;
    server_name ngoclinh2.tnut.cuong.id.vn;

    location / {
        root /usr/share/nginx/html/web2;
        index index.html;
    }

    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
